package main

import (
	"text/template"
)

var wiki = template.Must(template.New("wiki").Parse(wikiPage))

const wikiPage = `
== Introduction ==

The tables below lists the focal length equivalents between different formats.

The wide tables are keeping track of aspect ratios, such that every format can fit into any target format. In other words the equivalent format is strictly wider.

The horizontal tables take into account only the horizontal field of view.

The vertical tables take into account only the vertical field of view.

== Focal lens equivalents ==

{{$sensors := .Sensors}}

{{range .CameraInfo}}
=== {{.Name}} ===

{| class="wikitable"
|+ {{.Name}} (wide)
|-
|Focal legth
|Horizontal FOV
|Vertical FOV
{{- range $sensors}}
|{{.}}
{{- end}}
{{- range .Lenses }}
|-
|{{.Lens}}
|{{printf "%.1f" .HFoV}}
|{{printf "%.1f" .VFoV}} {{$li := .}}
{{- range $s := $sensors}}
|{{index $li.EqW $s | printf "%.0f"}}
{{- end}}
{{- end}}
|}

{| class="wikitable"
|+ {{.Name}} (horizontal)
|-
|Focal legth
|Horizontal FOV
|Vertical FOV
{{- range $sensors}}
|{{.}}
{{- end}}
{{- range .Lenses }}
|-
|{{.Lens}}
|{{printf "%.1f" .HFoV}}
|{{printf "%.1f" .VFoV}} {{$li := .}}
{{- range $s := $sensors}}
|{{index $li.EqH $s | printf "%.0f"}}
{{- end}}
{{- end}}
|}

{| class="wikitable"
|+ {{.Name}} (vertical)
|-
|Focal legth
|Horizontal FOV
|Vertical FOV
{{- range $sensors}}
|{{.}}
{{- end}}
{{- range .Lenses }}
|-
|{{.Lens}}
|{{printf "%.1f" .HFoV}}
|{{printf "%.1f" .VFoV}} {{$li := .}}
{{- range $s := $sensors}}
|{{index $li.EqV $s | printf "%.0f"}}
{{- end}}
{{- end}}
|}

{{end}}

== Code ==

This page was generated by https://mgk.ro/cmd/fovgen.
`

