7lfix:V:
	go install

test:V: 7lfix
	7lfix

cl:V: test
	foo=`mktemp -d`
	cp l.0/* $foo
	bash -c "cd $foo && hg init && hg add && hg commit -m zero"
	last=`ls -d l.? | tail -1`
	cp $last/* $foo
	bash -c "cd $foo && upload.py -m 7lfixtest"
	rm -rf $foo
