#!/bin/sh

# PROVIDE: go_import_redirector
# REQUIRE: DAEMON

. /etc/rc.subr

name=go_import_redirector
rcvar=go_import_redirector_enable
load_rc_config $name

pidfile="/var/run/${name}.pid"
command="/usr/local/sbin/go-import-redirector"
start_cmd=go_import_redirector_start
stop_postcmd=go_import_redirector_cleanup

go_import_redirector_start() {
	%%TOUCH%% ${pidfile}
	/usr/sbin/daemon -cf -p ${pidfile} ${viewvc_flags} ${command} ${go_import_redirector_flags}
}

go_import_redirector_cleanup() {
	[ -f ${pidfile} ] && %%RM%% ${pidfile}
}

run_rc_command "$1"
